name: lovespace
description: A complete couple app.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # المكتبات الأساسية
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  
  # خدمات فايربيز
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  
  # مكتبة الرفع (تم تحديثها لحل المشكلة)
  uploadcare_flutter: ^5.1.0
  
  # الوسائط والصوت
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  
  # أدوات مساعدة
  timeago: ^3.6.1
  uuid: ^4.3.3
  
  # حل مشكلة التعارض بإضافة هذه
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
